### PR TITLE
Enable Ambient Display

### PR DESCRIPTION
**Pull request by PL125**

### CODE REVIEW

**Comment by nikich340** [comment]
Heh, our devices don't have support for this option by hardware. What for is it then??

**Comment by PL125** [comment]
Sorry, I'm still learning, I make the pull request by mistake.
About ambient display I can confirm its working fine, I just need to check some logs.

**Comment by nikich340** [comment]
It's not working, we don't have hardware sensor for this (if this function enabled phone must enable screen when you take it in your hands).

**Comment by PL125** [comment]
You’re right but, but I think it’s still a nice feature. Our devices also lack the notification led so at least now we have some visual notification.

**Pull request closed without merging**
